import sofia from "../images/sofia.webp";

export const autoslidingcards = [
  {
    id: 1,
    title: "Delivery",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 2,
    title: "Cleaning",
    task: "Sofa Cleaning",
    price: "$450",
    image: sofia,
  },
  {
    id: 3,
    title: "Delivery",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 4,
    title: "Cleaning",
    task: "Sofa Cleaning",
    price: "$450",
    image: sofia,
  },
  {
    id: 5,
    title: "Delivery",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 6,
    title: "Cleaning",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 7,
    title: "Cleaning",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 8,
    title: "Delivery",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 9,
    title: "Cleaning",
    task: "Sofa Cleaning",
    price: "$450",
    image: sofia,
  },
  {
    id: 10,
    title: "Delivery",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 11,
    title: "Cleaning",
    task: "Sofa Cleaning",
    price: "$450",
    image: sofia,
  },
  {
    id: 12,
    title: "Delivery",
    task: "Sofa Delivery",
    price: "$450",
    image: sofia,
  },
  {
    id: 13,
    title: "Cleaning",
    task: "Sofa Cleaning",
    price: "$450",
    image: sofia,
  },
  {
    id: 14,
    title: "Cleaning",
    task: "Sofa Cleaning",
    price: "$450",
    image: sofia,
  },
];
